import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, ExternalLink, Film, GraduationCap, Mail, Menu, Play, Trophy, X } from 'lucide-react';

const profile = { name: 'Sir Montgomery', classYear: '2027', school: 'Clark High School', location: 'Las Vegas, Nevada', position: 'Combo guard · PG / SG', height: '6\'3"', weight: '175 lbs', gpa: '4.04 weighted', email: 'Sirgunner1@gmail.com', phone: '+1 (702) 712-1317', instagram: 'https://www.instagram.com/_sirskiiiii/', maxPreps: 'https://www.maxpreps.com/nv/las-vegas/clark-chargers/athletes/sir-montgomery/?careerid=bh7ufhgi3k299' };

const stats = [['4.2', 'APG', 'Team leader'], ['106', 'AST', '2025–26 total'], ['9.2', 'PPG', 'Season average'], ['1.3', 'SPG', 'Defensive impact']];
const film = [
  { title: 'Game film', label: 'Full-game and season film', image: '/assets/1242.jpg', description: 'Watch Sir create advantages, make the next pass, and control the pace of a possession.', href: '' },
  { title: 'Playmaking reel', label: 'Coming soon', image: '/assets/pg_action1.png', description: 'A curated highlight reel will be linked here when the final film URL is ready.', href: '' },
  { title: 'Defensive possessions', label: 'Coming soon', image: '/assets/DSC07012.JPEG', description: 'Perimeter pressure, communication, and two-way possessions from the championship season.', href: '' },
];
const exposure = [
  { school: 'University of Montana', detail: 'Mr. Grizz Award · MVP', type: 'Award' },
  { school: 'Southern Utah University', detail: 'Elite Camp · Top Performer', type: 'Camp' },
  { school: 'Long Beach State', detail: 'Nike Basketball Camp', type: 'Camp' },
  { school: 'Colorado State University', detail: 'Campus + basketball visit', type: 'Visit' },
];

function Header({ onContact }) {
  const [open, setOpen] = useState(false);
  const links = [['Profile', 'profile'], ['Film', 'film'], ['Accomplishments', 'accomplishments'], ['Exposure', 'exposure']];
  return <header className={`site-header ${open ? 'is-open' : ''}`}>
    <a className="brand" href="#top" onClick={() => setOpen(false)}><span>SIR</span><b>MONTGOMERY</b><small>CLASS OF 2027</small></a>
    <button className="menu-button" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    <nav className="nav-links" aria-label="Main navigation">{links.map(([label, href]) => <a key={href} href={`#${href}`} onClick={() => setOpen(false)}>{label}</a>)}<button className="nav-cta" onClick={() => { setOpen(false); onContact(); }}>Contact <ArrowRight size={15} /></button></nav>
  </header>;
}

function SectionLabel({ children, dark = false }) { return <p className={`section-label ${dark ? 'on-dark' : ''}`}><span />{children}</p>; }

function ContactPanel({ compact = false }) {
  const [sent, setSent] = useState(false);
  const [form, setForm] = useState({ name: '', organization: '', email: '', message: '' });
  const update = event => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = event => { event.preventDefault(); const body = `Hello,\n\n${form.message}\n\nName: ${form.name}\nOrganization: ${form.organization}\nReply to: ${form.email}`; window.location.href = `mailto:${profile.email}?subject=${encodeURIComponent(`Recruiting inquiry for Sir Montgomery — ${form.name}`)}&body=${encodeURIComponent(body)}`; setSent(true); };
  return <div className={`contact-panel ${compact ? 'compact' : ''}`}>
    <div className="contact-heading"><SectionLabel>Recruiting contact</SectionLabel><h2>Start a <em>conversation.</em></h2><p>Coaches, programs, and basketball contacts can request current film, schedule details, and Sir’s recruiting profile here.</p></div>
    <form onSubmit={submit}><div className="form-grid"><label>Your name<input name="name" value={form.name} onChange={update} required placeholder="Coach or representative" /></label><label>Program / organization<input name="organization" value={form.organization} onChange={update} required placeholder="College or program" /></label></div><label>Email address<input type="email" name="email" value={form.email} onChange={update} required placeholder="coach@college.edu" /></label><label>Message<textarea name="message" value={form.message} onChange={update} required rows="4" placeholder="What would you like to see or discuss?" /></label><button className="button button-gold" type="submit">Open recruiting email <ArrowRight size={17} /></button><p className="form-note">This opens your email app with a draft addressed to {profile.email}. Your message is not stored on this website.</p>{sent && <p className="form-status" role="status">Your email draft is ready. Send it from your email app to reach Sir’s recruiting contact.</p>}</form>
  </div>;
}

function FilmCard({ item }) { return <article className="film-card"><div className="film-image"><img src={item.image} alt="" /><span className="film-badge">{item.label}</span>{item.href ? <a className="play-button" href={item.href} target="_blank" rel="noreferrer" aria-label={`Watch ${item.title}`}><Play fill="currentColor" size={21} /></a> : <span className="play-button muted" aria-hidden="true"><Film size={19} /></span>}</div><div className="film-copy"><p className="eyebrow">{item.label}</p><h3>{item.title}</h3><p>{item.description}</p>{item.href ? <a className="inline-link" href={item.href} target="_blank" rel="noreferrer">Watch film <ExternalLink size={14} /></a> : <span className="inline-link disabled">Film link to be added <Film size={14} /></span>}</div></article>; }

function App() {
  const [contactOpen, setContactOpen] = useState(false);
  useEffect(() => { document.title = 'Sir Montgomery | College Basketball Recruiting'; }, []);
  const accomplishments = useMemo(() => [['State Champion', 'NIAA Class 4A · Clark High School'], ['NXTPro Champion', 'Prominent Elite 17U'], ['Offensive Player of the Year', 'AAU team honor']], []);
  const scrollContact = () => { setContactOpen(true); setTimeout(() => document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' }), 20); };
  return <div className="recruiting-site" id="top">
    <Header onContact={scrollContact} />
    <main>
      <section className="recruiting-hero"><img className="hero-background" src="/assets/1242.jpg" alt="Sir Montgomery finishing at the rim for Clark High School" /><div className="hero-shade" /><div className="hero-content"><div className="availability"><span />Class of {profile.classYear} · Recruiting profile</div><h1>Sir<br /><em>Montgomery.</em></h1><p className="hero-sub">A high-IQ combo guard who creates for others, competes on defense, and makes winning plays in big moments.</p><div className="hero-actions"><a href="#film" className="button button-gold">Watch film <Play size={15} fill="currentColor" /></a><a href="#profile" className="hero-text-link">View player profile <ArrowRight size={16} /></a></div></div><div className="hero-facts"><span>CLARK HIGH SCHOOL</span><b>PG · SG</b><span>LAS VEGAS, NV</span></div></section>
      <section className="quick-profile" id="profile"><div className="quick-inner"><div className="quick-intro"><SectionLabel>At a glance</SectionLabel><h2>A guard who<br /><em>raises the level.</em></h2><p>Sir Montgomery brings pace, poise, and purpose to every possession. His 2025–26 season ended with a state championship and team-leading playmaking numbers.</p><a href={profile.maxPreps} className="inline-link" target="_blank" rel="noreferrer">View public player profile <ExternalLink size={14} /></a></div><div className="identity-grid"><div><span>Position</span><strong>{profile.position}</strong></div><div><span>School</span><strong>{profile.school}</strong></div><div><span>Class</span><strong>{profile.classYear}</strong></div><div><span>Size</span><strong>{profile.height} · {profile.weight}</strong></div><div><span>Academics</span><strong>{profile.gpa} GPA</strong></div><div><span>Club</span><strong>Prominent Elite 17U</strong></div></div></div></section>
      <section className="stats-section"><div className="section-width"><div className="section-heading-row"><div><SectionLabel>2025–26 season</SectionLabel><h2>Production that<br /><em>travels.</em></h2></div><p>Verified Clark High School season statistics. Sir led the team in assists and finished the year as a state champion.</p></div><div className="stats-grid">{stats.map(([value, label, detail]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span><p>{detail}</p></div>)}</div></div></section>
      <section className="film-section" id="film"><div className="section-width"><div className="section-heading-row"><div><SectionLabel>Evaluate the game</SectionLabel><h2>Film tells<br /><em>the story.</em></h2></div><p>See the reads, decisions, and defensive effort behind the numbers. Film links can be updated in one place as new footage is released.</p></div><div className="film-grid">{film.map(item => <FilmCard item={item} key={item.title} />)}</div><div className="film-note"><Film size={18} /><p>Have a film link to add? <button onClick={scrollContact}>Send the recruiting contact a note <ArrowRight size={14} /></button></p></div></div></section>
      <section className="accomplishments-section" id="accomplishments"><div className="section-width"><div className="section-heading-row"><div><SectionLabel>Championship résumé</SectionLabel><h2>Proof in<br /><em>the moments.</em></h2></div><img className="award-graphic" src="/assets/1249.jpg" alt="Sir Montgomery named 17U Player of the Week" /></div><div className="accomplishment-list">{accomplishments.map(([title, detail], index) => <div className="accomplishment" key={title}><span>0{index + 1}</span><Trophy size={20} /><div><h3>{title}</h3><p>{detail}</p></div><CheckCircle2 size={18} /></div>)}</div></div></section>
      <section className="exposure-section" id="exposure"><div className="section-width"><div className="section-heading-row"><div><SectionLabel>College exposure</SectionLabel><h2>Already in<br /><em>the room.</em></h2></div><p>Camp and campus experiences are part of Sir’s ongoing development and recruiting story.</p></div><div className="exposure-grid">{exposure.map(item => <article className="exposure-card" key={item.school}><span>{item.type}</span><GraduationCap size={20} /><h3>{item.school}</h3><p>{item.detail}</p></article>)}</div><img className="team-photo" src="/assets/1248.jpg" alt="Prominent Elite 17U after winning the NXTPro championship" /></div></section>
      <section className="schedule-section"><div className="section-width"><div className="section-heading-row"><div><SectionLabel>Upcoming</SectionLabel><h2>Schedule +<br /><em>availability.</em></h2></div><p>Current event information for college coaches. Contact Sir’s recruiting representative for additional dates and updates.</p></div><div className="schedule-card"><div className="schedule-row"><div className="schedule-date"><strong>SEP 20</strong><span>2026</span></div><div><h3>Men’s College Basketball Prospect ID Showcase</h3><p>Los Angeles, California</p></div><button onClick={scrollContact} aria-label="Request schedule details"><ArrowRight /></button></div></div></div></section>
      <section className="profile-story"><div className="section-width profile-story-grid"><div className="story-image"><img src="/assets/1243.jpg" alt="Sir Montgomery taking a jump shot in a Clark High School uniform" /></div><div><SectionLabel>The player</SectionLabel><h2>Poised in the<br /><em>big moments.</em></h2><p>Sir is a point guard who sees the floor early, communicates with purpose, and stays composed when the game gets tight. His approach is team-first: make the right read, defend the next possession, and help the group win.</p><p>For a complete evaluation, pair his season numbers with his film and reach out for current recruiting information.</p><a className="button button-dark" href={profile.maxPreps} target="_blank" rel="noreferrer">Open player profile <ExternalLink size={15} /></a></div></div></section>
      <section className="contact-section" id="contact"><div className="section-width contact-layout"><div className="contact-aside"><SectionLabel>Recruiting contact</SectionLabel><h2>Let’s talk<br /><em>basketball.</em></h2><p>For college coaches and basketball programs: request current film, schedule information, academic details, or a conversation with Sir’s family contact.</p><a href={`mailto:${profile.email}`} className="contact-email"><Mail size={17} />{profile.email}</a><a href={`tel:${profile.phone.replace(/[^\d+]/g, '')}`} className="contact-email">{profile.phone}</a><a href={profile.instagram} target="_blank" rel="noreferrer" className="contact-social">Instagram · @_sirskiiiii <ExternalLink size={14} /></a></div><ContactPanel compact /></div></section>
    </main>
    <footer className="site-footer"><div className="section-width footer-grid"><div><a className="brand footer-brand" href="#top"><span>SIR</span><b>MONTGOMERY</b><small>CLASS OF 2027</small></a><p>Clark High School · Las Vegas, Nevada<br />Point guard / combo guard · Student-athlete</p></div><div><p className="footer-label">Explore</p><a href="#profile">Player profile</a><a href="#film">Film</a><a href="#accomplishments">Accomplishments</a><a href="#exposure">College exposure</a></div><div><p className="footer-label">For coaches</p><a href="#contact">Request information <ArrowRight size={14} /></a><a href={profile.maxPreps} target="_blank" rel="noreferrer">Public profile <ExternalLink size={14} /></a><a href={`mailto:${profile.email}`}>{profile.email}</a><a href={`tel:${profile.phone.replace(/[^\d+]/g, '')}`}>{profile.phone}</a></div></div><div className="footer-bottom section-width"><span>© {new Date().getFullYear()} Sir Montgomery</span><span>Recruiting profile · Class of 2027</span></div></footer>
    {contactOpen && <div className="contact-modal" role="dialog" aria-modal="true" aria-label="Recruiting contact"><div className="modal-inner"><button className="modal-close" onClick={() => setContactOpen(false)} aria-label="Close contact form"><X /></button><ContactPanel /></div></div>}
  </div>;
}

export default App;
